@startuml workflow_6

title Login; Attempts matchmaking;\nGets game; Stops polling

group login
Client -> Server: Login with valid credentials
Server -> Client: Provide session token
end

group matchmaking
Client -> Server: Request matchmaking ticket
Server -> Client: Send matchmaking ticket
Client -> Server: Polls for update (xN)
Server -> Client: Sends waiting notification (xN)
Client -> Server: Polls for update
Server -> Client: Sends game handle
end

group timeout
Server -> Server: Forfeits user
end

@enduml